name: Set up environment
description: Common environment setup steps for this repository

inputs:
  jdk:
    description: Set up JDK
    default: 'false'
  gradle:
    description: Set up Gradle
    default: 'false'
  brew:
    description: Set up Homebrew
    default: 'false'
    # Only some runners need this, for example see:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#homebrew-note
  ktfmt:
    description: Set up ktfmt
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up JDK
      if: ${{ inputs.jdk == 'true' || inputs.gradle == 'true' }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Set up Gradle
      if: ${{ inputs.gradle == 'true' }}
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
    - name: Set up Homebrew
      if: ${{ inputs.brew == 'true' || inputs.ktfmt == 'true' }}
      run: ./.github/actions/setup-environment/setup-homebrew.sh
      shell: bash
    - name: Set up ktfmt
      if: ${{ inputs.ktfmt == 'true' }}
      run: brew install ktfmt
      shell: bash
