name: Set up environment
description: Common environment setup steps for this repository

inputs:
  jdk:
    description: Set up JDK
    default: 'false'
  gradle:
    description: Set up Gradle
    default: 'false'
  gradle-daemon:
    description: If Gradle is set up, optionally disable the daemon
    default: 'true'


runs:
  using: composite
  steps:
    - name: Set up JDK
      if: ${{ inputs.jdk == 'true' || inputs.gradle == 'true' }}
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Set up Gradle
      if: ${{ inputs.gradle == 'true' }}
      uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
    - name: Disable Gradle daemon
      if: ${{ inputs.gradle == 'true' && inputs.gradle-daemon == 'false' }}
      run: echo "GRADLE_OPTS=-Dorg.gradle.daemon=false" >> "$GITHUB_ENV"
      shell: bash