name: pre-merge
on: pull_request
jobs:
  build-health:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          gradle: true
          gradle-daemon: false
      - name: Verify build health
        id: build-health
        run: ./gradlew :buildHealth
      - name: Publish build health report
        if: failure() && steps.build-health.outcome == 'failure'
        run: |
          echo "### Build health report" >> $GITHUB_STEP_SUMMARY
          cat "build/reports/dependency-analysis/build-health-report.txt" | tee -a $GITHUB_STEP_SUMMARY

  code-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          ktfmt: true
      - name: Verify code formatting
        run: scripts/check-code-formatting.sh
