name: pre-merge
on: pull_request

# Cancel in-progress/pending PR checks if a new commit is pushed to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          gradle: true
      - name: Run unit tests
        run: ./gradlew test --no-daemon

  build-health:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          gradle: true
      - name: Verify build health
        id: build-health
        run: ./gradlew :buildHealth --no-daemon
      - name: Publish build health report
        if: failure() && steps.build-health.outcome == 'failure'
        run: |
          echo "### Build health report" >> $GITHUB_STEP_SUMMARY
          cat "build/reports/dependency-analysis/build-health-report.txt" | tee -a $GITHUB_STEP_SUMMARY

  code-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          ktfmt: true
      - name: Verify code formatting
        run: scripts/check-code-formatting.sh
